# Generated by Django 5.0.6 on 2024-06-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='Employee',
        ),
    ]
