# Generated by Django 5.0.6 on 2024-06-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtapp', '0003_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='luffy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=30)),
            ],
        ),
    ]
